Tests: Use openjdk-8-jre explicitly instead of 'default-jre' in Dockerfile to avoid error 'java.lang.NoClassDefFoundError: javax/xml/ws/Holder' from Java 9